version: '3.8'

services:
  app:
    image: '3765ae574235'
    container_name: app
    ports:
      - '8184:8184'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=Timofey7828102
      - DB_URL=jdbc:postgresql://db:5432/focus-flow-habit-service
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Timofey7828102
      - POSTGRES_DB=focus-flow-habit-service

